IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu
IN=src
FROM=bash-prompt
FILE=library_scripts.sh

.PHONY: sync-files test-all test-autogenerated test-duplicate test-global test-scenarios

sync-files:
	find \
		./$(IN) \
		-maxdepth 1 \
		-type d \
		-not -wholename $(FROM) \
		-not -wholename './$(IN)' \
		-exec cp ./$(IN)/$(FROM)/$(FILE) {} \;

test-autogenerated:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--skip-scenarios \
		--skip-duplicated \
		--base-image $(IMAGE) \
		/workspaces/devcontainer-features

test-duplicate:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--skip-autogenerated \
		--skip-scenarios \
		--base-image $(IMAGE) \
		/workspaces/devcontainer-features

test-global:
	devcontainer features test \
		--global-scenarios-only \
		--remote-user root \
		--base-image $(IMAGE) \
		/workspaces/devcontainer-features

test-scenarios:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--skip-autogenerated \
		--skip-duplicated \
		/workspaces/devcontainer-features

test-all:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--base-image $(IMAGE) \
		/workspaces/devcontainer-features
