.PHONY: test-all test-autogenerated test-duplicate test-scenarios

test-autogenerated:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--skip-scenarios \
		--skip-duplicated \
		--base-image mcr.microsoft.com/devcontainers/base:ubuntu \
		/workspaces/devcontainer-features

test-scenarios:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--skip-autogenerated \
		--skip-duplicated \
		--base-image mcr.microsoft.com/devcontainers/base:ubuntu \
		/workspaces/devcontainer-features

test-duplicate:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--skip-autogenerated \
		--skip-scenarios \
		--base-image mcr.microsoft.com/devcontainers/base:ubuntu \
		/workspaces/devcontainer-features

test-all:
	devcontainer features test \
		--features $(FEATURE) \
		--remote-user root \
		--base-image mcr.microsoft.com/devcontainers/base:ubuntu \
		/workspaces/devcontainer-features
