name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tst-auto:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - adr-tools
          - bash-prompt
          - bash-sensible
          - custom-ca-cert
          - detect-secrets
          - pre-commit-cache
          - sbt-cache
          - scalafmt-native
          - shell-execute-custom-script
          - shell-source-custom-script
          - snyk-cli
          - zsh-completion-setup
          - zsh-prompt-currenttime
        baseImage:
          - bachowskimichal/devcontainer-test-ubuntu:v3
          - bachowskimichal/devcontainer-test-debian:v3
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios --skip-duplicated --remote-user root -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  tst-dup:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - adr-tools
          - bash-prompt
          - bash-sensible
          - custom-ca-cert
          - detect-secrets
          - pre-commit-cache
          - sbt-cache
          - scalafmt-native
          - shell-execute-custom-script
          - shell-source-custom-script
          - snyk-cli
          - zsh-completion-setup
          - zsh-prompt-currenttime
        baseImage:
          - bachowskimichal/devcontainer-test-ubuntu:v3
          - bachowskimichal/devcontainer-test-debian:v3
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios --skip-autogenerated --remote-user root -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  tst-scn:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - adr-tools
          - bash-prompt
          - bash-sensible
          - custom-ca-cert
          - detect-secrets
          - just-completion
          - pre-commit-cache
          - pre-commit-initialize
          - sbt-cache
          - scalafmt-native
          - shell-execute-custom-script
          - shell-source-custom-script
          - snyk-cli
          - zsh-completion-setup
          - zsh-prompt-currenttime
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated --skip-duplicated .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only --remote-user root -i bachowskimichal/devcontainer-test-ubuntu:v3 .
